// AUTO-GENERATED by scripts/build-blog.mjs — do not edit manually
// Generated: 2026-07-28T14:01:36.088Z

export const BLOG_CATEGORIES = {
  "guides": {
    "label": "Industry Guides",
    "description": "How-to guides and explainers for the auto dismantler industry"
  },
  "news": {
    "label": "Network Updates",
    "description": "New rooms, milestones, and member stories from the Hotline HQ network"
  },
  "market": {
    "label": "Parts Market",
    "description": "Popular parts, seasonal trends, and pricing insights from 500+ yards"
  }
};

export const BLOG_POSTS = [
  {
    slug: "best-places-to-sell-used-auto-parts-online",
    category: "guides",
    title: "Best Places to Sell Used Auto Parts Online — 7 Options Compared (2026)",
    description: "Compare the 7 best places to sell used auto parts online in 2026. Fees, speed, reach, and pros/cons for eBay, Facebook, Car-Part.com, and more.",
    date: "2026-07-28",
    readTime: "10 min read",
    author: { name: "Hotline HQ Team", role: "The team behind the largest voice parts network in the US" },
  },
  {
    slug: "used-auto-parts-near-me",
    category: "guides",
    title: "Used Auto Parts Near Me — How to Find Local Salvage Yards and Parts Fast",
    description: "Find used auto parts near me with 6 proven methods. Compare local salvage yards, junkyards, and online tools to get the right part fast and cheap.",
    date: "2026-07-28",
    readTime: "9 min read",
    author: { name: "Hotline HQ Team", role: "The team behind the largest voice parts network in the US" },
  },
  {
    slug: "where-to-buy-used-auto-parts",
    category: "guides",
    title: "Where to Buy Used Auto Parts — Online and Local Options Compared (2026)",
    description: "Best places to buy used auto parts in 2026 — online and local options compared by price, speed, reliability, and return policy.",
    date: "2026-07-28",
    readTime: "9 min read",
    author: { name: "Hotline HQ Team", role: "The team behind the largest voice parts network in the US" },
  },
  {
    slug: "auto-recycling-industry-statistics",
    category: "market",
    title: "Auto Recycling Industry Statistics 2026 — Market Size, Trends, and Growth",
    description: "Auto recycling industry statistics for 2026: $32B market size, 9,000+ US yards, 12-15M vehicles recycled yearly. Growth trends, EV impact, and regional data.",
    date: "2026-07-28",
    readTime: "10 min read",
    author: { name: "Hotline HQ Team", role: "The team behind the largest voice parts network in the US" },
    component: "BlogPost",
  },
  {
    slug: "most-valuable-used-auto-parts-to-sell",
    category: "market",
    title: "Most Valuable Used Auto Parts to Sell — What Dismantlers Should Pull First",
    description: "The most valuable used auto parts ranked by resale price. 15 parts across three value tiers with realistic 2026 pricing for salvage yards.",
    date: "2026-07-28",
    readTime: "9 min read",
    author: { name: "Hotline HQ Team", role: "The team behind the largest voice parts network in the US" },
    component: "BlogPost",
  },
  {
    slug: "auto-dismantler-business-guide",
    category: "guides",
    title: "Auto Dismantler Business Guide — How Salvage Yards Work in 2026",
    description: "US yards process 12M+ vehicles yearly, feeding a $32B parts market. Guide to buying, dismantling, inventory, selling, licensing, and environmental compliance.",
    date: "2026-07-09",
    readTime: "10 min read",
    author: { name: "Hotline HQ Team", role: "The team behind the largest voice parts network in the US" },
  },
  {
    slug: "find-used-auto-parts-online-guide",
    category: "guides",
    title: "How to Find Used Auto Parts Online: Every Method Compared",
    description: "Compare five ways to find used auto parts online, from databases with 200M+ listings to voice hotlines with 2-second response times. Ranked by speed and cost.",
    date: "2026-07-09",
    readTime: "8 min read",
    author: { name: "Hotline HQ Team", role: "The team behind the largest voice parts network in the US" },
  },
  {
    slug: "how-auto-parts-hotlines-work",
    category: "guides",
    title: "How Do Auto Parts Hotlines Work? Voice Networks Explained for Salvage Yards",
    description: "US auto recyclers generate $32B in annual sales across 9,000+ locations. Voice hotlines connect 100+ yards per broadcast with 2-second response times, replacing hour-long phone calls.",
    date: "2026-07-09",
    readTime: "9 min read",
    author: { name: "Hotline HQ Team", role: "The team behind the largest voice parts network in the US" },
    component: "HowItWorksPage",
  },
  {
    slug: "how-salvage-yards-sell-more-parts",
    category: "guides",
    title: "How Salvage Yards Sell More Parts - 5 Channels That Actually Work",
    description: "Five sales channels for salvage yards ranked by speed and real ROI. Voice hotlines deliver 2-second response times across 500+ connected dismantler yards.",
    date: "2026-07-09",
    readTime: "7 min read",
    author: { name: "Hotline HQ Team", role: "The team behind the largest voice parts network in the US" },
  },
  {
    slug: "partshotlines-vs-car-part-vs-hotline-hq",
    category: "guides",
    title: "PartsHotlines vs Car-Part.com vs Hotline HQ — Which Parts Network Fits Your Yard?",
    description: "An honest head-to-head comparison of PartsHotlines.com, Car-Part.com, and Hotline HQ — three used auto parts networks with very different approaches to connecting yards with buyers.",
    date: "2026-07-09",
    readTime: "8 min read",
    author: { name: "Hotline HQ Team", role: "The team behind the largest voice parts network in the US" },
  },
  {
    slug: "salvage-yard-software-compared",
    category: "guides",
    title: "Salvage Yard Software Compared — Inventory Tools for Auto Dismantlers",
    description: "An honest comparison of the top salvage yard software tools — Dismantly, YardSmart, Frazer, Car-Part Checkmate, and Yard Manager — plus where voice networks fit in.",
    date: "2026-07-09",
    readTime: "7 min read",
    author: { name: "Hotline HQ Team", role: "The team behind the largest voice parts network in the US" },
  },
  {
    slug: "most-requested-used-auto-parts",
    category: "market",
    title: "Most-Requested Used Auto Parts — What Dismantlers Should Stock",
    description: "First-party data from the Hotline HQ network showing the top 12 most-requested used auto parts and top 6 vehicle makes by request volume. Stock smarter, sell faster.",
    date: "2026-07-09",
    readTime: "7 min read",
    author: { name: "Hotline HQ Team", role: "The team behind the largest voice parts network in the US" },
    component: "BlogPost",
  },
  {
    slug: "used-auto-parts-pricing-guide",
    category: "market",
    title: "Used Auto Parts Pricing Guide — What Salvage Parts Cost in 2026",
    description: "Price ranges for the top 20 most-requested used auto parts in 2026. Compare costs at self-service yards, full-service yards, and online marketplaces.",
    date: "2026-07-09",
    readTime: "7 min read",
    author: { name: "Hotline HQ Team", role: "The team behind the largest voice parts network in the US" },
    component: "BlogPost",
  },
];

export function getPostsByCategory(category) {
  return BLOG_POSTS.filter(p => p.category === category).sort((a, b) => b.date.localeCompare(a.date));
}

export function getPostUrl(post) {
  return `/blog/${post.category}/${post.slug}`;
}

export function getCategoryUrl(category) {
  return `/blog/${category}`;
}
